- name: Setup webserver and copy custom webpage
  hosts: azure1,linux1
  become: yes
  tasks:
    - name: unInstall Apache For Ubuntu on Azure
      when: ansible_os_family == 'Debian'
      yum:
        name: apache
        state: absent

    - name: Recursively remove directory For Ubuntu on Azure
      when: ansible_os_family == 'Debian'
      ansible.builtin.file:
        path: /var/www/html
        state: absent

    - name: unInstall HttpD For Redhat on AWS
      when: ansible_os_family == 'RedHat'
      yum:
        name: httpd
        state: absent    


