linuxServer:
      hosts:
          linux1:
            ansible_host: 13.210.169.243
            ansible_ssh_private_key_file: key1.pem
            ansible_user: ec2-user

          azure1:
            ansible_host: 20.189.113.56
            ansible_ssh_private_key_file: isaac1_key.pem
            ansible_user: azureuser
:

          
